import type { AttractionSpot } from './types'

/** 上海迪士尼园区大致中心（公开坐标） */
export const PARK_CENTER = {
  latitude: 31.14555,
  longitude: 121.65655,
}

/**
 * 游乐/体验项目（依据官网「所有玩乐」游乐设施为主，含主要演出与见面）
 * GPS 为公开地图近似点，供原生 Map 标注
 */
export const ATTRACTIONS: AttractionSpot[] = [
  // —— 明日世界 ——
  {
    id: 'tron',
    name: '创极速光轮－雪佛兰呈献',
    land: '明日世界',
    category: 'attraction',
    x: 78,
    y: 28,
    latitude: 31.1458,
    longitude: 121.6622,
    tier: 'hot',
    intro: '旗舰过山车，建议开园直奔或傍晚回访。',
    thrill: '高强度',
  },
  {
    id: 'ironman',
    name: '漫威英雄总部：钢铁侠飞行器',
    land: '明日世界',
    category: 'attraction',
    x: 72,
    y: 42,
    latitude: 31.1450,
    longitude: 121.6610,
    tier: 'hot',
    intro: '室内飞行射击，适合避暑补刷。',
    thrill: '中等',
  },
  {
    id: 'buzz',
    name: '巴斯光年星际营救',
    land: '明日世界',
    category: 'attraction',
    x: 68,
    y: 55,
    latitude: 31.1442,
    longitude: 121.6605,
    tier: 'cold',
    intro: '射击互动，午峰分流好选择。',
    thrill: '轻松',
  },
  {
    id: 'jetpack',
    name: '喷气背包飞行器',
    land: '明日世界',
    category: 'attraction',
    x: 74,
    y: 50,
    latitude: 31.1448,
    longitude: 121.6615,
    tier: 'medium',
    intro: '旋转升空，有身高限制。',
    thrill: '中等',
  },
  {
    id: 'stitch',
    name: '太空对话史迪奇',
    land: '明日世界',
    category: 'attraction',
    x: 70,
    y: 48,
    latitude: 31.1445,
    longitude: 121.6612,
    tier: 'cold',
    intro: '互动剧场，轻松好玩。',
    thrill: '轻松',
  },
  {
    id: 'pixar_trip',
    name: '皮克斯奇旅',
    land: '明日世界',
    category: 'attraction',
    x: 76,
    y: 38,
    latitude: 31.1452,
    longitude: 121.6618,
    tier: 'medium',
    intro: '皮克斯主题互动体验。',
    thrill: '轻松',
  },
  {
    id: 'tron_challenge',
    name: '创界：雪佛兰数字挑战',
    land: '明日世界',
    category: 'attraction',
    x: 80,
    y: 32,
    latitude: 31.1460,
    longitude: 121.6625,
    tier: 'cold',
    intro: '数字互动挑战。',
    thrill: '轻松',
  },

  // —— 疯狂动物城 ——
  {
    id: 'zootopia_hot',
    name: '疯狂动物城：热力追踪',
    land: '疯狂动物城',
    category: 'attraction',
    x: 28,
    y: 58,
    latitude: 31.1448,
    longitude: 121.6528,
    tier: 'hot',
    intro: '与朱迪、尼克飙车追捕，顶流项目。',
    thrill: '中等·沉浸',
  },

  // —— 梦幻世界 ——
  {
    id: 'mine',
    name: '七个小矮人矿山车',
    land: '梦幻世界',
    category: 'attraction',
    x: 58,
    y: 38,
    latitude: 31.1446,
    longitude: 121.6588,
    tier: 'hot',
    intro: '家园区人气矿山车。',
    thrill: '中等',
  },
  {
    id: 'peterpan',
    name: '小飞侠天空奇遇',
    land: '梦幻世界',
    category: 'attraction',
    x: 52,
    y: 44,
    latitude: 31.1442,
    longitude: 121.6582,
    tier: 'medium',
    intro: '飞屋暗黑骑乘。',
    thrill: '轻松',
  },
  {
    id: 'pooh',
    name: '小熊维尼历险记',
    land: '梦幻世界',
    category: 'attraction',
    x: 50,
    y: 48,
    latitude: 31.1436,
    longitude: 121.6578,
    tier: 'cold',
    intro: '温馨暗黑骑乘。',
    thrill: '轻松',
  },
  {
    id: 'voyage',
    name: '晶彩奇航',
    land: '梦幻世界',
    category: 'attraction',
    x: 54,
    y: 36,
    latitude: 31.1440,
    longitude: 121.6585,
    tier: 'medium',
    intro: '船巡游，夜间更出片。',
    thrill: '轻松',
  },
  {
    id: 'alice_maze',
    name: '爱丽丝梦游仙境迷宫',
    land: '梦幻世界',
    category: 'attraction',
    x: 56,
    y: 42,
    latitude: 31.1439,
    longitude: 121.6590,
    tier: 'cold',
    intro: '户外迷宫漫步。',
    thrill: '轻松',
  },
  {
    id: 'hunny_pot',
    name: '旋转疯蜜罐',
    land: '梦幻世界',
    category: 'attraction',
    x: 48,
    y: 46,
    latitude: 31.1434,
    longitude: 121.6576,
    tier: 'cold',
    intro: '旋转茶杯类，亲子友好。',
    thrill: '轻松',
  },
  {
    id: 'castle_walk',
    name: '奇幻童话城堡',
    land: '梦幻世界',
    category: 'attraction',
    x: 50,
    y: 40,
    latitude: 31.1441,
    longitude: 121.6579,
    tier: 'medium',
    intro: '走进城堡打卡。',
    thrill: '轻松',
  },
  {
    id: 'once_upon_time',
    name: '漫游童话时光',
    land: '梦幻世界',
    category: 'attraction',
    x: 50,
    y: 40,
    latitude: 31.146034,
    longitude: 121.655137,
    tier: 'cold',
    intro: '步行探索经典童话场景，适合亲子慢慢看。',
    thrill: '轻松',
  },

  // —— 奇想花园 ——
  {
    id: 'dumbo',
    name: '小飞象',
    land: '奇想花园',
    category: 'attraction',
    x: 40,
    y: 32,
    latitude: 31.1438,
    longitude: 121.6565,
    tier: 'cold',
    intro: '亲子经典。',
    thrill: '轻松',
  },
  {
    id: 'carousel',
    name: '幻想曲旋转木马',
    land: '奇想花园',
    category: 'attraction',
    x: 36,
    y: 28,
    latitude: 31.1440,
    longitude: 121.6558,
    tier: 'medium',
    intro: '经典合影点。',
    thrill: '轻松',
  },
  {
    id: 'marvel_hq',
    name: '漫威英雄总部',
    land: '奇想花园',
    category: 'attraction',
    x: 38,
    y: 34,
    latitude: 31.1435,
    longitude: 121.6562,
    tier: 'medium',
    intro: '互动体验馆。',
    thrill: '轻松',
  },

  // —— 探险岛 ——
  {
    id: 'soaring',
    name: '翱翔·飞越地平线',
    land: '探险岛',
    category: 'attraction',
    x: 42,
    y: 62,
    latitude: 31.1418,
    longitude: 121.6565,
    tier: 'hot',
    intro: '飞行影院，体感强。',
    thrill: '中高强度',
  },
  {
    id: 'rapids',
    name: '雷鸣山漂流',
    land: '探险岛',
    category: 'attraction',
    x: 48,
    y: 72,
    latitude: 31.1408,
    longitude: 121.6572,
    tier: 'medium',
    intro: '夏季漂流，几乎必湿。',
    thrill: '中等·会湿',
  },
  {
    id: 'ropes',
    name: '古迹探索营的绳索挑战道',
    land: '探险岛',
    category: 'attraction',
    x: 44,
    y: 68,
    latitude: 31.1412,
    longitude: 121.6568,
    tier: 'medium',
    intro: '高空绳索，有身高限制。',
    thrill: '中等',
  },
  {
    id: 'vista_trail',
    name: '古迹探索营·探索步行道',
    land: '探险岛',
    category: 'attraction',
    x: 45,
    y: 68,
    latitude: 31.146151,
    longitude: 121.65994,
    tier: 'cold',
    intro: '步行探索瀑布与遗迹景观，可按体力自由安排。',
    thrill: '轻松',
  },
  {
    id: 'camp',
    name: '小勇者营地',
    land: '探险岛',
    category: 'attraction',
    x: 40,
    y: 70,
    latitude: 31.1405,
    longitude: 121.6560,
    tier: 'cold',
    intro: '儿童探索区。',
    thrill: '轻松',
  },

  // —— 宝藏湾 ——
  {
    id: 'pirates',
    name: '加勒比海盗——沉落宝藏之战',
    land: '宝藏湾',
    category: 'attraction',
    x: 22,
    y: 48,
    latitude: 31.1416,
    longitude: 121.6535,
    tier: 'hot',
    intro: '大型暗黑骑乘+水花。',
    thrill: '中等',
  },
  {
    id: 'canoe',
    name: '探险家独木舟',
    land: '宝藏湾',
    category: 'attraction',
    x: 18,
    y: 52,
    latitude: 31.1412,
    longitude: 121.6528,
    tier: 'cold',
    intro: '自己划船，可能溅水。',
    thrill: '轻松·会湿',
  },
  {
    id: 'siren',
    name: '探秘海妖复仇号',
    land: '宝藏湾',
    category: 'attraction',
    x: 20,
    y: 46,
    latitude: 31.1418,
    longitude: 121.6530,
    tier: 'cold',
    intro: '登船探索互动。',
    thrill: '轻松',
  },
  {
    id: 'shipwreck',
    name: '船奇戏水滩',
    land: '宝藏湾',
    category: 'attraction',
    x: 16,
    y: 50,
    latitude: 31.1410,
    longitude: 121.6525,
    tier: 'cold',
    intro: '戏水互动区。',
    thrill: '轻松',
  },

  // —— 玩具总动员 ——
  {
    id: 'rex_racer',
    name: '抱抱龙冲天赛车',
    land: '玩具总动员',
    category: 'attraction',
    x: 70,
    y: 68,
    latitude: 31.1412,
    longitude: 121.6608,
    tier: 'hot',
    intro: 'U 形轨道冲天，失重感强。',
    thrill: '高强度',
  },
  {
    id: 'woody_carnival',
    name: '胡迪牛仔嘉年华',
    land: '玩具总动员',
    category: 'attraction',
    x: 66,
    y: 74,
    latitude: 31.1406,
    longitude: 121.6602,
    tier: 'medium',
    intro: '转盘射击互动。',
    thrill: '轻松',
  },
  {
    id: 'slinky',
    name: '弹簧狗团团转',
    land: '玩具总动员',
    category: 'attraction',
    x: 68,
    y: 72,
    latitude: 31.1408,
    longitude: 121.6605,
    tier: 'cold',
    intro: '旋转亲子项目。',
    thrill: '轻松',
  },

  // —— 演出 ——
  {
    id: 'castle_show',
    name: '“奇妙之心”城堡秀',
    land: '奇想花园',
    category: 'show',
    x: 45,
    y: 35,
    latitude: 31.1439,
    longitude: 121.6575,
    tier: 'medium',
    intro: '城堡前舞台演出。',
    thrill: '观赏',
  },
  {
    id: 'illuminations',
    name: '奇梦之光幻影秀',
    land: '奇想花园',
    category: 'show',
    x: 42,
    y: 30,
    latitude: 31.1437,
    longitude: 121.6568,
    tier: 'hot',
    intro: '夜间光影水秀。',
    thrill: '观赏',
  },
  {
    id: 'parade',
    name: '米奇童话专列',
    land: '奇想花园',
    category: 'show',
    x: 44,
    y: 26,
    latitude: 31.1442,
    longitude: 121.6565,
    tier: 'hot',
    intro: '花车巡游。',
    thrill: '观赏',
  },
  {
    id: 'frozen_sing',
    name: '冰雪奇缘：欢唱盛会',
    land: '梦幻世界',
    category: 'show',
    x: 55,
    y: 40,
    latitude: 31.1444,
    longitude: 121.6586,
    tier: 'medium',
    intro: '室内舞台剧。',
    thrill: '观赏',
  },
  {
    id: 'jack_sparrow_stunt',
    name: '风暴来临：杰克船长之惊天特技大冒险',
    land: '宝藏湾',
    category: 'show',
    x: 24,
    y: 44,
    latitude: 31.1420,
    longitude: 121.6538,
    tier: 'medium',
    intro: '室内特技秀。',
    thrill: '观赏',
  },

  // —— 角色见面 ——
  {
    id: 'mickey_meet',
    name: '奇想花园见面会 - 与米奇见面',
    land: '奇想花园',
    category: 'character',
    x: 40,
    y: 28,
    latitude: 31.1443,
    longitude: 121.6568,
    tier: 'medium',
    intro: '经典米奇合影。',
    thrill: '轻松',
  },
  {
    id: 'duffy_meet',
    name: '米奇大街见面会 - 与达菲和朋友们见面',
    land: '米奇大街',
    category: 'character',
    x: 34,
    y: 20,
    latitude: 31.1450,
    longitude: 121.6555,
    tier: 'medium',
    intro: '达菲家族见面。',
    thrill: '轻松',
  },
  {
    id: 'judy_nick',
    name: '动物城警局招募中心 - 与朱迪和尼克见面',
    land: '疯狂动物城',
    category: 'character',
    x: 30,
    y: 56,
    latitude: 31.1450,
    longitude: 121.6532,
    tier: 'hot',
    intro: '动物城人气见面。',
    thrill: '轻松',
  },
  {
    id: 'linabell_meet',
    name: '萌友小站见面会 - 与玲娜贝儿见面',
    land: '探险岛',
    category: 'character',
    x: 38,
    y: 64,
    latitude: 31.1415,
    longitude: 121.6558,
    tier: 'hot',
    intro: '玲娜贝儿合影。',
    thrill: '轻松',
  },
]

/** 官网公开的常见票务档位（金额可手改；价格会随日历变动） */
export const TICKET_PRESETS = [
  { id: 'day_475', kind: 'day_ticket' as const, name: '乐园门票·常规日', price: 475 },
  { id: 'day_539', kind: 'day_ticket' as const, name: '乐园门票·特别常规日', price: 539 },
  { id: 'day_599', kind: 'day_ticket' as const, name: '乐园门票·高峰档', price: 599 },
  { id: 'day_659', kind: 'day_ticket' as const, name: '乐园门票·较高峰档', price: 659 },
  { id: 'day_719', kind: 'day_ticket' as const, name: '乐园门票·高峰日', price: 719 },
  { id: 'day_799', kind: 'day_ticket' as const, name: '乐园门票·特别高峰日', price: 799 },
  { id: 'premier_single', kind: 'premier_access' as const, name: '迪士尼尊享卡·单项', price: 150 },
  { id: 'premier_bundle', kind: 'premier_access' as const, name: '迪士尼尊享卡·多项目套装', price: 600 },
  { id: 'early_entry', kind: 'early_entry' as const, name: '乐园早享卡', price: 140 },
] as const

export const PASS_PRESETS = [
  { id: 'pearl', name: '幻彩珍珠卡', price: 1399, days: 200, ticketFace: 499 },
  { id: 'jade', name: '奇梦翡翠卡', price: 2599, days: 300, ticketFace: 599 },
  { id: 'diamond', name: '无限钻石卡', price: 4399, days: 365, ticketFace: 699 },
] as const

/** 兼容旧简称匹配 */
export function normalizeRideName(name: string): string {
  const sourceId = Object.entries(OFFICIAL_ATTRACTION_SOURCE).find(([, item]) => item.sourceName === name)?.[0]
  const spot = sourceId ? ATTRACTIONS.find((item) => item.id === sourceId) : undefined
  if (spot) return spot.name
  if (name.includes('创极速光轮')) return '创极速光轮－雪佛兰呈献'
  if (name.includes('翱翔') && name.includes('地平线')) return '翱翔·飞越地平线'
  return name
}

/** ThemeParks.wiki 当前 31 个官方设施名与坐标；用于完整地图与中英文归一。 */
export const OFFICIAL_ATTRACTION_SOURCE: Record<
  string,
  { sourceName: string; latitude: number; longitude: number }
> = {
  shipwreck: { sourceName: 'Shipwreck Shore', latitude: 31.147249, longitude: 121.657735 },
  jetpack: { sourceName: 'Jet Packs', latitude: 31.143744, longitude: 121.654418 },
  vista_trail: { sourceName: 'Vista Trail at Camp Discovery', latitude: 31.146151, longitude: 121.65994 },
  zootopia_hot: { sourceName: 'Zootopia: Hot Pursuit', latitude: 31.148394, longitude: 121.655585 },
  pixar_trip: { sourceName: 'Pixar Adventurous Journey', latitude: 31.143161, longitude: 121.653161 },
  rapids: { sourceName: 'Roaring Rapids', latitude: 31.145285, longitude: 121.658906 },
  woody_carnival: { sourceName: 'Woody’s Roundup', latitude: 31.146217, longitude: 121.653061 },
  hunny_pot: { sourceName: 'Hunny Pot Spin', latitude: 31.147559, longitude: 121.654623 },
  pooh: { sourceName: 'The Many Adventures of Winnie the Pooh', latitude: 31.147827, longitude: 121.654597 },
  ropes: { sourceName: 'Challenge Trails at Camp Discovery', latitude: 31.145887, longitude: 121.659737 },
  camp: { sourceName: 'Junior Explorers Camp', latitude: 31.145573, longitude: 121.659171 },
  pirates: { sourceName: 'Pirates of the Caribbean Battle for the Sunken Treasure', latitude: 31.147542, longitude: 121.657507 },
  mine: { sourceName: 'Seven Dwarfs Mine Train', latitude: 31.147253, longitude: 121.65555 },
  buzz: { sourceName: 'Buzz Lightyear Planet Rescue', latitude: 31.143325, longitude: 121.653499 },
  once_upon_time: { sourceName: '“Once Upon a Time” Adventure', latitude: 31.146034, longitude: 121.655137 },
  rex_racer: { sourceName: 'Rex’s Racer', latitude: 31.145515, longitude: 121.652404 },
  alice_maze: { sourceName: 'Alice in Wonderland Maze', latitude: 31.146843, longitude: 121.655461 },
  ironman: { sourceName: 'Become Iron Man at the Marvel Universe', latitude: 31.144675, longitude: 121.654372 },
  stitch: { sourceName: 'Space Chat With Stitch', latitude: 31.143539, longitude: 121.65404 },
  voyage: { sourceName: 'Voyage to the Crystal Grotto', latitude: 31.145811, longitude: 121.654268 },
  dumbo: { sourceName: 'Dumbo the Flying Elephant', latitude: 31.144846, longitude: 121.655649 },
  castle_walk: { sourceName: 'Enchanted Storybook Castle', latitude: 31.14602, longitude: 121.655408 },
  canoe: { sourceName: 'Explorer Canoes', latitude: 31.145922, longitude: 121.65784 },
  carousel: { sourceName: 'Fantasia Carousel', latitude: 31.144788, longitude: 121.657117 },
  siren: { sourceName: "Siren's Revenge", latitude: 31.147323, longitude: 121.658621 },
  marvel_hq: { sourceName: 'Marvel Universe', latitude: 31.144544, longitude: 121.654688 },
  slinky: { sourceName: 'Slinky Dog Spin', latitude: 31.14538, longitude: 121.65283 },
  tron_challenge: { sourceName: 'TRON Realm, Chevrolet Digital Challenge', latitude: 31.143806, longitude: 121.652574 },
  peterpan: { sourceName: 'Peter Pan’s Flight', latitude: 31.145785, longitude: 121.653645 },
  tron: { sourceName: 'TRON Lightcycle Power Run – Presented by Chevrolet', latitude: 31.144241, longitude: 121.652545 },
  soaring: { sourceName: 'Soaring Over the Horizon', latitude: 31.146205, longitude: 121.660809 },
}

export const OFFICIAL_ATTRACTION_COUNT = Object.keys(OFFICIAL_ATTRACTION_SOURCE).length

export function mapLocationFor(spot: AttractionSpot) {
  return OFFICIAL_ATTRACTION_SOURCE[spot.id] || {
    latitude: spot.latitude,
    longitude: spot.longitude,
  }
}
